spring:
  application:
    name: doctor-contact-service
  graphql:
    cors:
      allow-credentials: true
      allowed-origins:
        - http://localhost:3000
    graphiql:
      enabled: true

webclient:
  clients:
    doctorContactApi:
      url: "http://localhost:8000/api"
      timeout: 3500